version: "3.8"
services: 
    mongodb:
        image: 'mongo' 
        volumes: 
            - data:/data/db
        #environment: 
        #    - MONGO_INITDB_ROOT_USERNAME=max
        #    - MONGO_INITDB_ROOT_PASSWORD=secret      
        env_file: 
            - ./env/mongo.env
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '80:80'
        #environment: 
        #    - MONGODB_USERNAME=max
        #    - MONGODB_PASSWORD=secret
        env_file:
            - ./env/backend.env
        volumes: 
            - logs:/app/logs
        depends_on: 
            - mongodb              
    frontend:   
        build: ./frontend
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        depends_on: 
            - backend    

volumes: 
    data:
    logs:    